### ISSUE TITLE
RTM Incompatiblity with CustomNPCs and Other Mods that Add .ogg Files

### ISSUE THREAD

**Issue by PumpkingP13** [fixrtm/fixRTM#111]
When I try to run CustomNPCs with RTM (in the recent version for 1.12.2), the game suddenly crashes. It's the same when I tried to run RTM and a voice pack for LittleMaidMods together. Here's a crash log of the instance of running CustomNPCs and RTM together. Hope it helps!

[crash-2020-07-30_10.05.10-client.txt](https://github.com/fixrtm/fixRTM/files/5002736/crash-2020-07-30_10.05.10-client.txt)

**Comment by anatawa12** [comment]
@PumpkingP13 Are you using Scripting in CustomNPCs?

**Comment by anatawa12** [comment]
No response for one year. Closing
