### ISSUE TITLE
Crash after landing the NPC in the train with a leash.

### ISSUE THREAD

**Issue by Trollebas** [fixrtm/fixRTM#114]
[crash-2020-08-31_11.35.56-server.txt](https://github.com/fixrtm/fixRTM/files/5152106/crash-2020-08-31_11.35.56-server.txt)
https://youtu.be/SmoPnHBsOmc?t=2638

**Comment by anatawa12** [comment]
The problem crashing when landing the NPC in the train with a leash could not be reproduced.
But the crash report says crashed when the NPC get off the train by AI. So I fixed this problem.
