### ISSUE TITLE
Incompatibility with LittleTiles

### ISSUE THREAD

**Issue by Dushess** [fixrtm/fixRTM#164]
Yes, pretty neat mod with great possibilities, but not forking with RTM completely.
Your mod partially fixes that, but RTM's content loader fails to work and no any variable element will be loaded after server start.

[28.txt](https://github.com/fixrtm/fixRTM/files/6078137/28.txt)
This is my log with processing of the issue and with modlist.

Hope you can do something on your side, maybe.

**Comment by anatawa12** [comment]
what does any variable element mean?

**Comment by Dushess** [comment]
It meands anything that can be changed but is one class. Like any version of track or any version of diesel train.

**Comment by anatawa12** [comment]
You think ModelPacks aren't loaded, don't you?
How do you think that? If you think that because there is no 'Construct Model' nor 'Registr resource' logs, this is fixRTM's changes. fixRTM moves those logs to TRACE level, not shown in console output. If you want to see those log, you can disable this change by `reduceConstructModelLog` flag in fix-rtm.cfg.

**Comment by Dushess** [comment]
btw on server connection the content manager window shows no progress, like I've not connected to a world. Not good just as is, but we dunno what might be else in there.

**Comment by anatawa12** [comment]
What does 'content manager window' mean? Which mod is it?

**Comment by Dushess** [comment]
the window appears on minecraft loading and later should show every module loading into a world, including additional packs.

**Comment by anatawa12** [comment]
![image](https://user-images.githubusercontent.com/22656849/110224851-eacf4580-7f22-11eb-80b6-9a8d3c63adde.png)

is this window? this window is shown only at starting Minecraft and not shown at starting Minecraft Server.

> on server connection the content manager window shows no progress

what do you mean 'on server connection'? RTM requires (or it's recommended) to wait until finish loading all model packs so the window should not be shown at connecting to some server or loading some world.

**Comment by Dushess** [comment]
It's from RTM, no idea how it does that, but this version uses old method and starts to load things (in that window) only when world is loaded.

**Comment by anatawa12** [comment]
Not reproduced.

- The forge server with NGTLib, RTM, fixRTM, CreativeCore, and LittleTiles looks running successfully
- The Minecraft client with those mods looks running successfully

**Comment by Dushess** [comment]
Weird, because I'm still dropping into networks list somehow on first launch, after I'm on map, but still not loaded the content in RTM aux window. Tried latest recommended forge, latest versions of used mods and something is wrong. Gonne check more...

**Comment by Dushess** [comment]
This https://pastebin.com/U8dup2Lz

**Comment by Dushess** [comment]
Out of ideas : |

**Comment by anatawa12** [comment]
@Dushess I'm sorry long time no response. I found a bug in NGTLib but it looks not like a compatibility issue. I'll fix the bug and release snapshot soon. Could you check if some bug still exists?

**Comment by Dushess** [comment]
fixed with latest updates, there is some issues with railways and rarely curve function, but overall is ok.
