### ISSUE TITLE
DiscordSRV入りサーバーとの相性が悪い

### ISSUE THREAD

**Issue by line-0707** [fixrtm/fixRTM#193]
joumeymap-1.12.2-5.7.1
MCTE2.4.10-24
NGTLib2.4.18-35
RTM2.4.21-40
AsphaltMod_2.3.7_mc1.12.2と
DiscordSRVを導入したmohistサーバーにおいて当modを導入すると途中まで起動する(読み込まれる)ものの結局固まって動かなくなったそうです。
(代理投稿)これ以上の詳しいことはTwitterの@S_TREC1125までお願いします。

**Comment by anatawa12** [comment]
Relates https://github.com/Mohist-Community/Mohist/issues/577
過去に再現していたことを確認しました。対応は少々お待ち下さい

**Comment by anatawa12** [comment]
Relates Mohist-Community/Mohist#577
過去に再現していたことを確認しました。対応は少々お待ち下さい

**Comment by anatawa12** [comment]
mohistへの変更が取り入れられたようなので、mohist #\200にて動作確認をしていただきたいです。 S_TREC1125さんの方にはこちらから連絡させていただこうと思います
