### ISSUE TITLE
Tool anomalies

### ISSUE THREAD

**Issue by hksz** [fixrtm/fixRTM#220]
When I load it, the tool will become exceptionally
Minecraft Forge 14.23.5.2855
![2021-06-11_00 28 04](https://user-images.githubusercontent.com/51861438/121565361-f87af680-ca4e-11eb-8c93-942f5672f287.png)

**Comment by hksz** [comment]
Server using "mohist-1.12.2-227-server"

**Comment by anatawa12** [comment]
@hksz 

Please specify your fixRTM, RTM, NGTLib, and Forge Version.

**Comment by hksz** [comment]
> @hksz
> 
> Please specify your fixRTM, RTM, NGTLib, and Forge Version.

fixRtm-2.0.18
RTM2.4.21-40_forge-1.12.2-14.23.2.2611
NGTLib2.4.18-35_forge-1.12.2-14.23.2.2611
Forge 14.23.5.2855
