### ISSUE TITLE
Model error？

### ISSUE THREAD

**Issue by hksz** [fixrtm/fixRTM#232]
When using RTM on the server, there is always a model transformation, no problem with a single person
This seems to be a legacy issue?
Hope to fix it

Error Video：https://youtu.be/_c0nW1Kl6v0

Server Core：mohist-1.12.2-227

RTM2.4.21-40_forge-1.12.2-14.23.2.2611
NGTLib2.4.18-35_forge-1.12.2-14.23.2.2611
fixRtm-SNAPSHOT-2021-06-13-13-32-47
1.12.2-Forge 14.23.5.2855

**Comment by anatawa12** [comment]
@hksz 
What's the single world? Is it a reference or a copy of the server's one? Is it happens with single only world?

I've understand multiplay probrem.

**Comment by hksz** [comment]
> @hksz
> What's the single world? Is it a reference or a copy of the server's one? Is it happens with single only world?
> 
> I've understand multiplay probrem.
I mean there is no problem with single player, there is a problem with multiplayer

**Comment by hksz** [comment]
Hopefully it will be fixed in the future!
