### ISSUE TITLE
Game crash when editing the green line

### ISSUE THREAD

**Issue by CacPixel** [fixrtm/fixRTM#289]
### Before submitting a bug, please make sure following checks.

- [X] You have finished loading all model packs before login to world/server.
- [X] You're using the latest stable, snapshot, or daily-snapshot version of fixRTM.
- [X] You're using correct version of RTM and NGTLib for your fixRTM.
- [X] You couldn't find same bag in the issues.

### Descrive the bug

![Screenshot_2021-08-22_18 07 35](https://user-images.githubusercontent.com/31470772/130351829-b19d8257-0f50-49bb-a6fb-8f0f88d7810e.png)
[latest.log](https://github.com/fixrtm/fixRTM/files/7027150/latest.log)

When editing the green line, the game crashed without responding.
Please see the video below.
Crash-report file was not generated.

### To Reproduce

https://user-images.githubusercontent.com/31470772/130351786-38445f94-9fc4-4e5f-b8c6-4dd95124038b.mp4

### OS

Windows 10 21H1

### Minecraft Forge Version

2852

### fixRTM Version

SNAPSHOT-2021-08-19-NIGHTLY / 2.0.19

**Comment by anatawa12** [comment]
@CAC233 Can you check if some file starting with 'hs_err' is in your game profile folder? (game profile folder is a directory contains mods folder.) It may have good information about crash. if exists, please give me the file. It also be a crash report.

**Comment by anatawa12** [comment]
@CAC233 Did you manually stop the Minecraft? If possible, please do not stop manually even if 'Application is not responding' dialog is shown by windows.

**Comment by CAC233** [comment]
> @CAC233 Can you check if some file starting with 'hs_err' is in your game profile folder? (game profile folder is a directory contains mods folder.) It may have good information about crash. if exists, please give me the file. It also be a crash report.

I have the hs_err file but it was generated 1 month ago because of out of memory.

**Comment by CAC233** [comment]
> @CAC233 Did you manually stop the Minecraft? If possible, please do not stop manually even if 'Application is not responding' dialog is shown by windows. If you didn't try without stopping Minecraft manually, Could you try without stopping Minecraft manually?

Several minutes passed, still not responding.

**Comment by anatawa12** [comment]
> > @CAC233 Did you manually stop the Minecraft? If possible, please do not stop manually even if 'Application is not responding' dialog is shown by windows. If you didn't try without stopping Minecraft manually, Could you try without stopping Minecraft manually?
> 
> 
> 
> Several minutes passed, still not responding.


Still now? if so, please stop minecraft manually. Ill create a tool to check what's happening in few days.

**Comment by CAC233** [comment]
> @CAC233 Did you manually stop the Minecraft? If possible, please do not stop manually even if 'Application is not responding' dialog is shown by windows. If you didn't try without stopping Minecraft manually, Could you try without stopping Minecraft manually?

still not responding.

**Comment by CAC233** [comment]
> > > @CAC233 Did you manually stop the Minecraft? If possible, please do not stop manually even if 'Application is not responding' dialog is shown by windows. If you didn't try without stopping Minecraft manually, Could you try without stopping Minecraft manually?
> > 
> > 
> > Several minutes passed, still not responding.
> 
> Still now? if so, please stop minecraft manually. Ill create a tool to check what's happening in few days.

Thanks!

**Comment by anatawa12** [comment]
@CAC233 I've finished making the tool to get more information: [jstack-gui]. Could you follow the following instructions?

1. Please make sure JDK is installed on your PC. 
  1. If you didn't install JDK, please install from [adoptium][adoptium8]. 
  2. After installing JDK, please restart your PC.
2. Download [jstack-gui lastet] and install into mods
3. Please launch Minecraft. Another window named "jstack gui" will be appeared.
4. Play Minecraft and make Minecraft frozen.
5. Click "run jstack" in "jstack gui" window.
6. Please let me know the text in textarea.

[adoptium8]: https://adoptium.net/?variant=openjdk8&jvmVariant=hotspot.
[jstack-gui]: https://github.com/anatawa12/jstack-gui
[jstack-gui lastet]: https://github.com/anatawa12/jstack-gui/releases/latest

**Comment by CacPixel** [comment]
I finally found that the Betterfps Mod caused this problem. It's not fixRTM's fault. Now the game never crashes when editing the green line!
