### ISSUE TITLE
NoClassDefFoundError: net.minecraft.entity.EntityTracker

### ISSUE THREAD

**Issue by letsdank** [fixrtm/fixRTM#401]
### Before submitting a bug, please make sure following checks.

- [X] You have finished loading all model packs before login to world/server.
- [X] You're using the latest stable, snapshot, or daily-snapshot version of fixRTM.
- [X] You're using correct version of RTM and NGTLib for your fixRTM.
- [X] You couldn't find same bag in the issues.

### Descrive the bug

An error is occurring when I try to start an integrated server (open world).
I tried to remove FoamFix (though that's the main problem), but it doesn't work.
[Crashreport](https://github.com/fixrtm/fixRTM/files/7966046/crash-2022-01-30_16.57.48-server.txt)
[Latest log](https://github.com/fixrtm/fixRTM/files/7966047/latest.log)
[Debug log](https://github.com/fixrtm/fixRTM/files/7966048/debug.log)

### To Reproduce

* Install next mods: 
![image](https://user-images.githubusercontent.com/47483026/151703289-2382868c-1be1-468b-8f0f-6932ced377cc.png)
* Wait for load additional RTM packs
* Join in any world

### OS

Windows 10 Enterprise 21H1 19043.1288

### Minecraft Forge Version

14.23.5.2860

### fixRTM Version

2.0.20

### Other Mods

Chiesels and Bits, CodeChickenLib, CubicChunks, FlatColorBlock-HexFinder, FlatColoredBlocks, FoamFix, ForgeMultipart, MorePlayerModels, NGTLib 2.4.19, Optifine HD U G5, RailCraft, WorldEdit, WirelessRedstone

**Comment by anatawa12** [comment]
Duplicates #365
