### ISSUE TITLE
特定の場合、車両連結の情報を保存できません

### ISSUE THREAD

**Issue by CreeperKong** [fixrtm/fixRTM#410]
### Before submitting a bug, please make sure following checks.

- [X] You have finished loading all model packs before login to world/server.
- [X] You're using the latest stable, snapshot, or daily-snapshot version of fixRTM.
- [X] You're using correct version of RTM and NGTLib for your fixRTM.
- [X] You couldn't find same bag in the issues.

### Descrive the bug

カーブや勾配がある軌道に列車が止まると、ゲームを再起動すると車両連結の情報が失われます

### To Reproduce

1. 車両を連結する
2. カーブや勾配がある軌道まで列車を走らせる
3. タイトルをもどる
4. ゲームを終了
5. ゲームを起動
6. ワールドをロード

### Expected Behavior

車両連結の情報を保存できる

### Actual Behavior

車両連結の情報が失われます

### OS

Windows 11 21H２

### Minecraft Forge Version

2860

### fixRTM Version

2.0.20

**Comment by anatawa12** [comment]
@CreeperKong おまたせしてすみません。本日再現を試みたところ、カーブ、坂共におそらく再現できました。

私の環境では再ログイン後、GUIのFormationでは1両編成となっていましたが、ログアウト前にもともと連結されていた台車を連結モードにするためにバールで叩くと"連結解除"とチャットで表示されます。同様の現象が発生するか確認していただきたいです。

動画では開発環境の関係上、"連結モード”, "連結解除”のチャットメッセージが"message.train.concatenation_mode" "message.train.concatenated"となっていますが無視していただきたいです。

https://user-images.githubusercontent.com/22656849/154831694-8f4081d7-0a32-4a90-8b8c-cddc11e51a58.mp4

**Comment by CreeperKong** [comment]
同じ現象ではありません

バールで叩くと"連結モード"と表示されます。

走行すると連結解除後と同じになります

**Comment by anatawa12** [comment]
わかりました。ありがとうございます。

もし可能であれば、ワールドのロード〜Formationの確認、そして運転すると一両のみ動くところまでを画面録画していただきたいです。

Windows11ですので、[こちら][windows-recording] を参考にしてください。

よろしくおねがいします。



[windows-recording]: https://hamachan.info/win10-win-movie/#st-toc-h-3
[apple-help-recording]: https://support.apple.com/ja-jp/HT208721

**Comment by CreeperKong** [comment]
https://youtu.be/xx9bDlbv7L8

こちらの画面録画をご覧ください

ログファイルを添付します

- [latest.log](https://github.com/fixrtm/fixRTM/files/8106914/latest.log)
- [2022-02-21-1.log.gz](https://github.com/fixrtm/fixRTM/files/8106916/2022-02-21-1.log.gz)
- [2022-02-21-2.log.gz](https://github.com/fixrtm/fixRTM/files/8106917/2022-02-21-2.log.gz)
- [2022-02-21-3.log.gz](https://github.com/fixrtm/fixRTM/files/8106918/2022-02-21-3.log.gz)

**Comment by anatawa12** [comment]
画面録画とログありがとうございます。

再現ができないため、デフォルト車両である223系で再現できるかを教えていただきたいです。もし再現できない場合は使用しているモデルパックを添付していただきたいです。(再配布が許可されていない場合はダウンロードリンクを貼っていただきたいです。)
また、可能であれば再現可能なワールドデータをいただきたいです。

**Comment by CreeperKong** [comment]
223系の場合は先ほど再現したバグです

> @CreeperKong おまたせしてすみません。本日再現を試みたところ、カーブ、坂共におそらく再現できました。
> 
> 私の環境では再ログイン後、GUIのFormationでは1両編成となっていましたが、ログアウト前にもともと連結されていた台車を連結モードにするためにバールで叩くと"連結解除"とチャットで表示されます。同様の現象が発生するか確認していただきたいです。
> 
> 動画では開発環境の関係上、"連結モード”, "連結解除”のチャットメッセージが"message.train.concatenation_mode" "message.train.concatenated"となっていますが無視していただきたいです。
> 
>  Screen.Recording.2022-02-20.at.15.35.56.mp4

このモデルパックを使用すると、両方の状況が発生する可能性があります

モデルパック：
https://minato.xrea.jp/2020/07/31/minatocommutertrainb/
特殊発光セット

ワールドデータ：
[fixrtmbugreport.zip](https://github.com/fixrtm/fixRTM/files/8140470/fixrtmbugreport.zip)

ログ：
[2022-02-25-1.log.gz](https://github.com/fixrtm/fixRTM/files/8140473/2022-02-25-1.log.gz)
[2022-02-25-2.log.gz](https://github.com/fixrtm/fixRTM/files/8140475/2022-02-25-2.log.gz)
[latest.log](https://github.com/fixrtm/fixRTM/files/8140476/latest.log)

**Comment by anatawa12** [comment]
ありがとうございます。

ログ内で確認でき、ダウンロードできたmod(以下の表参照)を導入してテストしましたが、
Windows 11の公式ランチャー及びHello Minecraft Launcher環境で再現することができませんでした。

お手数ですが公式ランチャーで、fixRTM(及びその前提であるForge, NGTLib, RTM)のみの環境で再現できるかを教えていただきたいです。

| mod                                          | version      |
|----------------------------------------------|--------------|
| davincisvessels                              | 6.340        |
| rtm                                          | 2.4.21       |
| fix-rtm                                      | 2.0.20       |
| xaerominimap_core                            | 1.12.2-1.0   |
| movingelevators                              | 1.2.34       |
| movingworld                                  | 1.12-6.353   |
| mcte                                         | 2.4.11       |
| forge                                        | 14.23.5.2860 |
| xaeroworldmap_core                           | 1.12.2-1.0   |
| com.elytradev.movingworld.common.asm.coremod | 6.353        |
| flammpfeil.slashblade                        | mc1.12-r33   |
| mcp                                          | 9.42         |
| ngtlib                                       | 2.4.18       |
| xaerominimapfair                             | 22.1.0       |
| xaeroworldmap                                | 1.20.0       |
| OptiFine                                     | HD U G5      |

モデルパック:

- ```600v`sPCpack.zip```
- `[AR]AR110.zip`
- `[RTM]Tobu30000pack_n.zip`
- `[RTM]秋豆ホームドア.zip`
- `Dc30_HM_8th.zip`
- `hi03SoundLib.zip`
- `JNR_Ec205_Mi.zip`
- `KS_keiseiPackv2.0.zip`
- `KS_OM3000Packv2.0.zip`
- `KS_SkyLinerPackv1.0.zip`
- `KS_新交通システムパックvβ.zip`
- `MCTA_6door.zip`
- `MCTA_base.zip`
- `MCTA_RL.zip`
- `MCTB_base.zip`
- `MCTB_RL.zip`
- `MhnElecSoundlib.zip`
- `TrainPack_ENODEN_v1.2_by_hojyo.zip`
- `TrainPack_JNR103_v1.31_by_hojyo.zip`
- `TrainPack_JRWDc120_v1.1_by_hojyo.zip`

**Comment by CreeperKong** [comment]
ご迷惑をおかけして申し訳ありません。

時々あなたが言ったことを起こります

> @CreeperKong おまたせしてすみません。本日再現を試みたところ、カーブ、坂共におそらく再現できました。
> 
> 私の環境では再ログイン後、GUIのFormationでは1両編成となっていましたが、ログアウト前にもともと連結されていた台車を連結モードにするためにバールで叩くと"連結解除"とチャットで表示されます。同様の現象が発生するか確認していただきたいです。
> 
> 動画では開発環境の関係上、"連結モード”, "連結解除”のチャットメッセージが"message.train.concatenation_mode" "message.train.concatenated"となっていますが無視していただきたいです。
> 
>  Screen.Recording.2022-02-20.at.15.35.56.mp4


中国版マイクラのアンチチートプログラムをアンインストールした後、前にわたしを説明した状況がありませんでした 。

このプログラムがすべてのJavaプロセスをインジェクするために、fixRTMがなしの場合も問題が発生しました。
この問題はNetease Gamesに報告されています。

**Comment by anatawa12** [comment]
Japanese(My native language)

ごめんなさい。別件で忙しく返信が遅くなりました。
失礼になってしまいますが、あなたの日本語は意味を理解するのが著しく難しい物となってしまっています。
もし可能であればあなたの母語(おそらく中国語)と自動翻訳後を併記していただきたいです。
また、[こちらのコメント]を併記して再送信していただきたいです。

English(My secondary language)

I'm so sorry to be late. I was busy with other projects.

I don't mean to be rude, but your Japanese is remarkably difficult to understand the meaning for me.
If possible, can you write in both your native language (probably Chinese) and Japanese automatically translated?
And can you re-submit [this comment] with your native language?

[こちらのコメント]: https://github.com/fixrtm/fixRTM/issues/410#issuecomment-1054184277
[this comment]: https://github.com/fixrtm/fixRTM/issues/410#issuecomment-1054184277

**Comment by CreeperKong** [comment]
I'm really sorry for causing troubles and misunderstandings.
Also I feel very sorry for reporting without deeper research on the issue.

When I uninstalled Minecraft China's anti-cheat program, the issue I described above has been resolved.
> 223系の場合は先ほど再現したバグです
> 
> > @CreeperKong おまたせしてすみません。本日再現を試みたところ、カーブ、坂共におそらく再現できました。
> > 私の環境では再ログイン後、GUIのFormationでは1両編成となっていましたが、ログアウト前にもともと連結されていた台車を連結モードにするためにバールで叩くと"連結解除"とチャットで表示されます。同様の現象が発生するか確認していただきたいです。
> > 動画では開発環境の関係上、"連結モード”, "連結解除”のチャットメッセージが"message.train.concatenation_mode" "message.train.concatenated"となっていますが無視していただきたいです。
> > Screen.Recording.2022-02-20.at.15.35.56.mp4
> 
> このモデルパックを使用すると、両方の状況が発生する可能性があります
> 
> モデルパック： https://minato.xrea.jp/2020/07/31/minatocommutertrainb/ 特殊発光セット
> 
> ワールドデータ： [fixrtmbugreport.zip](https://github.com/fixrtm/fixRTM/files/8140470/fixrtmbugreport.zip)
> 
> ログ： [2022-02-25-1.log.gz](https://github.com/fixrtm/fixRTM/files/8140473/2022-02-25-1.log.gz) [2022-02-25-2.log.gz](https://github.com/fixrtm/fixRTM/files/8140475/2022-02-25-2.log.gz) [latest.log](https://github.com/fixrtm/fixRTM/files/8140476/latest.log)


This anti-cheat program will inject all the java processes existing on my PC, which causes compatibility issues with some mods, not only fixRTM but also Davincivessels. I've reported this to Netease on March 1st and they had fixed this on March 8th.


However this issue described before still exists.


> @CreeperKong おまたせしてすみません。本日再現を試みたところ、カーブ、坂共におそらく再現できました。
> 
> 私の環境では再ログイン後、GUIのFormationでは1両編成となっていましたが、ログアウト前にもともと連結されていた台車を連結モードにするためにバールで叩くと"連結解除"とチャットで表示されます。同様の現象が発生するか確認していただきたいです。
> 
> 動画では開発環境の関係上、"連結モード”, "連結解除”のチャットメッセージが"message.train.concatenation_mode" "message.train.concatenated"となっていますが無視していただきたいです。
> 
>  Screen.Recording.2022-02-20.at.15.35.56.mp4

**Comment by anatawa12** [comment]
Thank you for providing in English! It makes me understood. 
Because the problem is a little differ than this issue describes so I've made another new issue (#429) and I'm closing this issue. if you want to get noticed about updates of the new issue, you can subscribe the new issue.
thank you for your bug reporting!
