### ISSUE TITLE
Cannot delete trains via command

### ISSUE THREAD

**Issue by CreeperKong** [fixrtm/fixRTM#477]
### Before submitting a bug, please make sure following checks.

- [X] You have finished loading all model packs before login to world/server.
- [X] You're using the latest stable, snapshot, or daily-snapshot version of fixRTM.
- [X] You're using correct version of RTM and NGTLib for your fixRTM.
- [X] You couldn't find same bag in the issues.

### Descrive the bug

I cannot delete all train with `/rtm delAllTrain`.
Both in server and singleplayer.

### To Reproduce

Singleplayer
[https://www.youtube.com/watch?v=qLnFfGCk6R0](https://www.youtube.com/watch?v=qLnFfGCk6R0)
log: [single-2022-06-07-1.log.gz](https://github.com/fixrtm/fixRTM/files/8853435/single-2022-06-07-1.log.gz)

Multiplayer
[https://youtu.be/nPwLPhxd_dw](https://youtu.be/nPwLPhxd_dw)
log:
client [multi-client-2022-06-07-2.log.gz](https://github.com/fixrtm/fixRTM/files/8853432/multi-client-2022-06-07-2.log.gz)
server [multi-server-debug.log.gz](https://github.com/fixrtm/fixRTM/files/8853434/multi-server-debug.log.gz)

(I use catserver as the server software, it has better optimization for multi-thread and supports to load forge,bukkit,spigot addons)
[https://catmc.org/](https://catmc.org/)

### Expected Behavior

All trains should be removed.

### Actual Behavior

Nothing happened

### OS

Windows 11 22H2

### Minecraft Forge Version

2860

### fixRTM Version

2.0.21-rc2

**Comment by anatawa12** [comment]
I reproduced this bug. Thank you for reporting!
