### ISSUE TITLE
Insulator and wire data fails to be saved

### ISSUE THREAD

**Issue by CreeperKong** [fixrtm/fixRTM#487]
### Before submitting a bug, please make sure following checks.

- [X] You have finished loading all model packs before login to world/server.
- [X] You're using the latest stable, snapshot, or daily-snapshot version of fixRTM.
- [X] You're using correct version of RTM and NGTLib for your fixRTM.
- [X] You couldn't find same bag in the issues.

### Descrive the bug

Insulator and wire data fails to save after leaving the chunk or disconnecting.

### To Reproduce

Steps:
1. Right click with insulator and wire, bring up the menu, and select another type.
2. Put 2 insulators, then connect them with wire.
3. Quit game
4. Login into game and the save
5. Wiring is missing & insulators back to default type.

Log: 
[2022-04-29-5.log.gz](https://github.com/fixrtm/fixRTM/files/8972877/2022-04-29-5.log.gz)

### OS

Red Hat Enterprise Linux 8.6 (On my server)

### Minecraft Forge Version

2860

### fixRTM Version

2.0.21

**Comment by anatawa12** [comment]
it maybe loading failed with #486. I'll fix soon.
