### ISSUE TITLE
破壊系アイテムの制限

### ISSUE THREAD

**Issue by PIPOsen-0801** [fixrtm/fixRTM#586]
### Feature report check list

- [X] 最新のSNAPSHOTバージョンの fixRTM にその機能が存在しないこと
- [X] issues でそのリクエストがまだ無いこと。

### Describe the feature

破壊系アイテム(主に銃)の入手や使用を制限するconfigまたはpermissionを作って欲しいです。

**Comment by anatawa12** [comment]
useGunパーミッションではだめでしょうか

**Comment by PIPOsen-0801** [comment]
コマンドのみの管理だと、管理し辛いと思ったので...

**Comment by PIPOsen-0801** [comment]
configというのは/permitコマンドと同じことを言ってました。すみません。
permissionというのは具体的に言うと、グループごとで権限を管理したく、例えばdefaultグループでは全てのfixRTMの権限がfalseで制限され、adminグループではnegative.useRazorのみがfalseで制限される、といったことをしたいと思いました。

**Comment by anatawa12** [comment]
つまりはパーミッションシステムにグループ機能がほしいということでしょうか？
fixRTMの1プロジェクトとして[plugin-permissions-for-ngt]というbukkitのパーミッションをNGTLibの/permitの仕組みで扱うためのmodがあります。

[plugin-permissions-for-ngt]: https://github.com/fixrtm/plugin-permissions-for-ngt

**Comment by PIPOsen-0801** [comment]
そんなものがあったんですね(それで大丈夫です!)、自分の調べ不足でした。教えていただきありがとうございます。
