### ISSUE TITLE
走行中に反対側の運転席に座ると逆走する

### ISSUE THREAD

**Issue by PIPOsen-0801** [fixrtm/fixRTM#593]
### バグ報告の前に、以下の点を確認していただきたいです。

- [X] Server や World にはいる前に、全ての ModelPack の読み込みを終えている
- [X] 最新の SNAPSHOT, nightly-snapshot, またはリリースの fixRTM を使用してる
- [X] 正しい RTM 及び NGTLib を使用している。
- [X] 同じバグが issues で見つからない

### Descrive the bug

走行中に反対側の運転席に座ると逆走します。併結時も各運転席にて同様です。マルチプレイにおいても正しい運転席にて運転する人と別のプレイヤーが反対側の運転席に座ると逆走します。また、最後尾の運転席にプレイヤーが座っている状態で、最前の運転席に別のプレイヤーが座ると、最後尾の前の運転席に移動してしまいます。(これによって車掌乗務ができない)

### To Reproduce

・シングルプレイでの再現
1. 列車を走らせます
2. 走らせながら降ります
3. 適当な号車の後ろの台車(運転席)に座ります
4. 逆走を始めます

・マルチプレイでの再現
1. プレイヤー２が車掌という体で最後尾の運転席に座ります
2. プレイヤー１が運転士という体で最前の運転席に座り発車します
3. プレイヤー２はその車両の前台車の運転席にテレポートします
4. プレイヤー２がその車両の最後尾の運転席に戻ると逆走します

### Expected Behavior

運転されている席以外の運転席のレバーサを中にする？

### OS

Windows8.1 Version6.3

### Minecraft Forge Version

14.23.5.2859

### fixRTM Version

7.0.24

**Comment by anatawa12** [comment]
実装のデザインを見る限り、そもそも運転者以外が運転席に乗ることをあまり想定されていないようなため、修正には時間がかかりそうです。

**Comment by anatawa12** [comment]
Fixed by #633

**Comment by PIPOsen-0801** [comment]
[2.0.26-beta.1](https://github.com/fixrtm/fixRTM/releases/tag/2.0.26-beta.1)の一部状態において、この症状が治っていなかったため連絡させていただきます。
単行列車の場合は治っていました。しかし複数両の編成だと逆走してしまいます。

**Comment by PIPOsen-0801** [comment]
複数両の編成で、先頭車前方の運転席から前に動かしている場合
・先頭車後方の運転席に乗る→徐々に現象して逆走を始める
・二両目以降の後方の運転

https://github.com/fixrtm/fixRTM/assets/80109295/71cf3f37-4330-43cc-a02a-1a6dc71ac731

席に乗る→逆走を始める

**Comment by Kai-Z-JP** [comment]
KaizPatchではCabSideを実装することでこれを解決しました。
参考までに: https://github.com/Kai-Z-JP/KaizPatchX/pull/368

**Comment by anatawa12** [comment]
色々調査した結果、CabSideを実装したほうが良さそうですね。実装お借りします。
