### ISSUE TITLE
Redstone Signal converter config cannot be saved

### ISSUE THREAD

**Issue by CreeperKong** [fixrtm/fixRTM#595]
### Before submitting a bug, please make sure following checks.

- [X] You have finished loading all model packs before login to world/server.
- [X] You're using the latest stable, snapshot, or daily-snapshot version of fixRTM.
- [X] You're using correct version of RTM and NGTLib for your fixRTM.
- [X] You couldn't find same bag in the issues.

### Descrive the bug

Redstone to signal converter have a settings page to configure the signal number.

### To Reproduce

Place a Redstone to signal converter, right click to set values != 0.
Then relogin into game

### Expected Behavior

Settings should be saved

### Actual Behavior

Settings not saved and returns to 0

### OS

Ubuntu Server 22.04

### Minecraft Forge Version

2860

### fixRTM Version

2.0.24

**Comment by CreeperKong** [comment]
[2022-12-24-3.log.gz](https://github.com/fixrtm/fixRTM/files/10298643/2022-12-24-3.log.gz)
Here is the log file

**Comment by anatawa12** [comment]
It looks it's actually saved but it doesn't synced to client so we see the data not synced.
