### ISSUE TITLE
Signal Converter cannot take over data when multiserver restart

### ISSUE THREAD

**Issue by PIPOsen-0801** [fixrtm/fixRTM#601]
### Before submitting a bug, please make sure following checks.

- [X] You have finished loading all model packs before login to world/server.
- [X] You're using the latest stable, snapshot, or daily-snapshot version of fixRTM.
- [X] You're using correct version of RTM and NGTLib for your fixRTM.
- [X] You couldn't find same bag in the issues.

### Descrive the bug

When I restart the multiserver, Signal converter value will be reset.

### To Reproduce

Set the signal converter value to another number in the multiserver.
Multiserver restarting resets the value to 0.

### OS

Windows8.1 Version6.3

### Minecraft Forge Version

14.23.5.2859

### fixRTM Version

2.0.24

**Comment by anatawa12** [comment]
#595

**Comment by PIPOsen-0801** [comment]
Openのやつしか重複確認してませんでした、すみません。
