### ISSUE TITLE
pack.jsonによるversionチェックが機能しない

### ISSUE THREAD

**Issue by PIPOsen-0801** [fixrtm/fixRTM#606]
### バグ報告の前に、以下の点を確認していただきたいです。

- [X] Server や World にはいる前に、全ての ModelPack の読み込みを終えている
- [x] 最新の SNAPSHOT, nightly-snapshot, またはリリースの fixRTM を使用してる
- [X] 正しい RTM 及び NGTLib を使用している。
- [X] 同じバグが issues で見つからない

### Descrive the bug

pack.jsonによるversionチェックが機能しない

### To Reproduce

https://onedrive.live.com/?authkey=%21ACk-mEUC_7mf5lU&id=F58928BACD47B1F5%211365&cid=F58928BACD47B1F5
RTMモデルパック作成キット_2.4.8_1+SRCにある通り、pack.jsonにてversionチェックの内容を書き、versionをずらす。
パックのロードを終え、ワールドを開いた時に通知が表示されない。
(同様の動作を1.7.10で試したら正常に通知されました)

### OS

Windows8.1 Version6.3

### Minecraft Forge Version

14.23.5.2859

### fixRTM Version

2.0.24

**Comment by anatawa12** [comment]
latest.logを提供してください。再現できませんでした。

**Comment by PIPOsen-0801** [comment]
再現ができないというのは通知が表示されたということですか？
もしpack.jsonが必要でしたらパックも送りましょうか。
logは今夜送りますね。

**Comment by PIPOsen-0801** [comment]
https://cdn.discordapp.com/attachments/1002157847586549861/1063037277015658526/logs.cab

**Comment by anatawa12** [comment]
> 再現ができないというのは通知が表示されたということですか？

はい。

> .cabファイル

今回はツールを使用して展開しますが今後はWindows固有の圧縮形式ではなくmac, Linuxでも一般的に使用されてる形式(.zip, .gz, .tar.gz等)を使用してください。こちらもコミュニティルールに明記してなかったため修正します。

**Comment by anatawa12** [comment]
> ```
> [18:58:56] [NGT Version Check/INFO] [STDERR]: [jp.ngt.ngtlib.util.VersionChecker$VersionCheckThread:run:108]: java.io.IOException: Server returned HTTP response code: 429 for URL: https://dl.dropboxusercontent.com/s/4dxg83j6rocd0ls/version.txt
> [18:58:56] [NGT Version Check/INFO] [STDERR]: [jp.ngt.ngtlib.util.VersionChecker$VersionCheckThread:run:108]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1839)
> [18:58:56] [NGT Version Check/INFO] [STDERR]: [jp.ngt.ngtlib.util.VersionChecker$VersionCheckThread:run:108]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
> [18:58:56] [NGT Version Check/INFO] [STDERR]: [jp.ngt.ngtlib.util.VersionChecker$VersionCheckThread:run:108]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
> [18:58:56] [NGT Version Check/INFO] [STDERR]: [jp.ngt.ngtlib.util.VersionChecker$VersionCheckThread:run:108]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430)
> [18:58:56] [NGT Version Check/INFO] [STDERR]: [jp.ngt.ngtlib.util.VersionChecker$VersionCheckThread:run:108]: 	at java.security.AccessController.doPrivileged(Native Method)
> [18:58:56] [NGT Version Check/INFO] [STDERR]: [jp.ngt.ngtlib.util.VersionChecker$VersionCheckThread:run:108]: 	at java.security.AccessController.doPrivileged(AccessController.java:713)
> [18:58:56] [NGT Version Check/INFO] [STDERR]: [jp.ngt.ngtlib.util.VersionChecker$VersionCheckThread:run:108]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429)
> [18:58:56] [NGT Version Check/INFO] [STDERR]: [jp.ngt.ngtlib.util.VersionChecker$VersionCheckThread:run:108]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
> [18:58:56] [NGT Version Check/INFO] [STDERR]: [jp.ngt.ngtlib.util.VersionChecker$VersionCheckThread:run:108]: 	at java.net.URL.openStream(URL.java:1038)
> [18:58:56] [NGT Version Check/INFO] [STDERR]: [jp.ngt.ngtlib.util.VersionChecker$VersionCheckThread:run:108]: 	at jp.ngt.ngtlib.util.VersionChecker$VersionCheckThread.run(VersionChecker.java:97)
> ```

一つでもversion.txtのダウンロードにエラーが発生するとどうやら一切機能しなくなってしまうようです。これを改善します。

**Comment by PIPOsen-0801** [comment]
圧縮形式の件、お詫び申し上げます。
改善の程お願いします。
エラーが発生していたということは私のpack.jsonに不備があったということでしょうか？
