### ISSUE TITLE
Execute scripts from pre-compiled cache

### ISSUE THREAD

**Issue by Siro256** [fixrtm/fixRTM#612]
### Feature report check list

- [X] What you want is not included in the latest snapshot version of fixRTM.
- [X] You couldn't find same request in the issues.

### Describe the feature

The implementation of NGTLib script executer have issue that compile script on every execution, makes conspicuous performance issue for bigger script. (e.g., Rendering script is compiled every frames.)
Create pre-compiled script cache on forge initialization event and execute from that. Shouldn't compile every-time.

現在のNGTLibの実装ではスクリプトを実行するたびにコンパイルしており、スクリプトが大きくなるほど顕著にパフォーマンスが低下するという問題を抱えています。(Render scriptの場合、毎フレームコンパイルしていることになる)
実行時に毎回コンパイルするのではなく、初回でキャッシュを作成したうえでそこから引いてくる実装へ変更するべきです。

**Comment by anatawa12** [comment]
私も再確認させていただきますが、少なくとも描画スクリプトについては初期化時にコンパイル・実行したものに含まれる関数使用してるはずですが毎回コンパイルしているという根拠はどちらになるでしょうか？

**Comment by anatawa12** [comment]
再確認しましたが毎フレームの再コンパイルは確認できませんでした。
