### ISSUE TITLE
ActionPartsの判定の改善

### ISSUE THREAD

**Issue by PIPOsen-0801** [fixrtm/fixRTM#623]
### バグ報告の前に、以下の点を確認していただきたいです。

- [X] Server や World にはいる前に、全ての ModelPack の読み込みを終えている
- [X] 最新の SNAPSHOT, nightly-snapshot, またはリリースの fixRTM を使用してる
- [X] 正しい RTM 及び NGTLib を使用している。
- [X] 同じバグが issues で見つからない

### Descrive the bug

ActionPartsを登録することによって、ボタンやレバーを作成できますが、その判定に難があります。

### To Reproduce

RenderScriptでのParts定義にてActionPartsを登録すると、render functionにてOUTLINE(253)とPICK(255)のpassが追加され、右クリックした際にはfunction onRightClickが実行されます。passの描画ではそれぞれ白い縁(カーソルが触れた時)、オレンジの縁(かつ右クリックされた時)がつきます。この時カーソルに触れているかどうかに関わらず、右クリックした時に反応してしまいます。また、プレイヤーの距離に関わらずどんなに離れたところから右クリックしても反応してしまいます。

これらはデフォルトで追加されている近江鉄道の車両の車掌スイッチで再現できます。
(これについてもう一つ問題があり、恐らく再現しようとすると引っかかるので書かさせていただきます。)
列車の方向が逆向きの時にentity.syncVehicleState(TrainState.TrainStateType.Door,数値);を実行した時の動作が異常で、値を1にすると2に、2にしようとすると1になります。

### Expected Behavior

カーソルの当たり判定の改善
・OUTLINEでの当たり判定は正常なので、PICKやonRightClickでの判定に問題があると思われます。(OUTLINEで検知した判定を利用できませんかね)

距離の判定の改善
・クリエイティブ、サバイバルでプレイヤーがブロックを設置、破壊できる距離(それぞれ5、4ブロック分でしたっけ)に検知距離を絞る
・インベントリ開いているときは反応しないようにする

### OS

Windows 8.1

### Minecraft Forge Version

2859

### fixRTM Version

2.0.24

**Comment by anatawa12** [comment]
ActionPartsの判定についてはアイテム持ってる状態でもアイテムと重ねて反応したり問題が山積みなため将来的に色々やろうと考えてましたがとりあえず距離制限とインベントリの方だけの選考実装は検討してみます。

**Comment by anatawa12** [comment]
> この時カーソルに触れているかどうかに関わらず、右クリックした時に反応してしまいます。

については右クリックしながら視点を移動して触れたときを指してるという解釈で間違いないでしょうか？

**Comment by anatawa12** [comment]
> カーソルの当たり判定の改善
・OUTLINEでの当たり判定は正常なので、PICKやonRightClickでの判定に問題があると思われます。(OUTLINEで検知した判定を利用できませんかね)

ActionPartsの仕様を勘違いしているかもしれないです。
ActionPartsはこのように実装されています。

1. OpenGLの機能を用いて選択されたオブジェクトを認識する
   1. PICKパスにて選択対象のすべてのオブジェクトを描画する
   2. OpenGLからカーソルにかぶる位置にあるActionPartsを教えてもらう
2. OUTLINEパスにて選択されたオブジェクトの輪郭を描画する
   1. OUTLINEパスとしてスクリプトを起動する
   2. `ActionParts.render`内部にて自身が1.で決まった選択対象であれば描画し、そうでなければ描画しない

そのため、PICKパスが常に呼び出されることを指しているのであればそれは正常な動作です。

**Comment by PIPOsen-0801** [comment]
> > この時カーソルに触れているかどうかに関わらず、右クリックした時に反応してしまいます。
> 
> については右クリックしながら視点を移動して触れたときを指してるという解釈で間違いないでしょうか？

いえ、違います。
列車を動かしていると、途中から不具合が発生します。クリックし始めた段階でActionPartsに触れていなくてもクリックが検知されてしまいます。この時、白い輪郭線の描画は正常です。クリックがご検知された時、オレンジの輪郭も描画されます。

**Comment by anatawa12** [comment]
> 列車を動かしていると、途中から不具合が発生します。クリックし始めた段階でActionPartsに触れていなくてもクリックが検知されてしまいます。

クリックが検知されたタイミングではActionPartsに触れていますか？

**Comment by PIPOsen-0801** [comment]
触れてないです

**Comment by anatawa12** [comment]
> シェーダーを入れた場合にこの現象が発生します

了解です。PICK等のPASSは描画に関わってないため、シェーダを無効化できないか少し試してみます。

> もしシェーダーを入れて試してみても再現ができない場合、動画を送ります。

デバッグ環境にてシェーダを導入するのに少し手間がかかるため、すぐに確認できないためシェーダの入った状態の動画は先にいただきたいです。

**Comment by PIPOsen-0801** [comment]
こんばんは。返信が遅れたことお詫び申し上げます。
まずこちらの動画では、列車の方向が逆向きの時にentity.syncVehicleState(TrainState.TrainStateType.Door,数値);を実行した時の動作が異常であることを再現しています。
https://github.com/fixrtm/fixRTM/assets/80109295/1d0e23a7-7946-4baf-819b-fd48c6289cf8

次にこちらの動画で、シェーダーを導入した時にカーソルに触れていなくてもクリック時に反応してしまう現象を再現しました。

https://github.com/fixrtm/fixRTM/assets/80109295/1cd081c3-afb3-46dc-9b75-c3c714fb621b

**Comment by anatawa12** [comment]
動画による説明ありがとうございます。

ActionPartsの影modに関係する部分は #659 に、syncVehicleStateの話は #658 に分離させていただきました。

影modに関係ない遠いActionPartsとGUI開きながらの話は #651 にて修正したためcloseさせていただきます。
