### ISSUE TITLE
Fixing crash when selecting textures in CustomNPCs

### ISSUE THREAD

**Issue by ym1025** [fixrtm/fixRTM#671]
### Feature report check list

- [X] What you want is not included in the latest snapshot version of fixRTM.
- [X] You couldn't find same request in the issues.

### Describe the feature

English:
This mod solved the problem of RTM and CustomNPCs conflicting and crashing when starting minecraft, but there is still the problem of CustomNPCs crashing when clicking the "Select Texture" button in the NPC settings screen. We would appreciate it if you could fix it.

Japanese(my mother tongue)
このmodでRTMとCustomNPCsがminecraftの起動時に競合しクラッシュする問題は解決しましたが、まだCustomNPCsのNPC設定画面で「テクスチャを選択」ボタンをクリックするとクラッシュしてしまう問題は残っています。修正していただけると幸いです。

Crash report: https://hastebin.com/share/wiwuhevedo.yaml

**Comment by anatawa12** [comment]
Could you try this version? https://github.com/fixrtm/fixRTM/pull/675#issuecomment-1605998900
