### ISSUE TITLE
Use binary search to reduce time when initializing BezierCurve

### ISSUE THREAD

**Issue by CacPixel** [fixrtm/fixRTM#710]
### Feature report check list

- [X] What you want is not included in the latest snapshot version of fixRTM.
- [X] You couldn't find same request in the issues.

### Describe the feature

In original RTM, a very simple search method is used when initializing normalizedParameters: search the required result from the start of an array. It's too slow when the bezier curve is very long and it directly runs on client thread(when onChangeRailShape, editing lines) or server thread(when creating rails). Use binary search algorithm instead of the original one can reduce the time spent a lot.
I tested on my mod, 120ms->1ms when invoking initNP(), 400m long curve.
![Screenshot_2024-02-26_20-10-35](https://github.com/fixrtm/fixRTM/assets/31470772/209dca4e-e122-4490-9b93-ff242c99092b)
![Screenshot_2024-02-26_20-11-06](https://github.com/fixrtm/fixRTM/assets/31470772/bc92d4fb-0159-43c0-90a8-2167a36440be)

**Comment by anatawa12** [comment]
implemented in #713
